In [1]:
import numpy as np

In [2]:
inp=np.array([[0,0],
     [0,1],
     [1,0],
     [1,1]])

In [3]:
op=np.array([0,1,1,0])
op=op.reshape(-1,1)
print(op)

[[0]
 [1]
 [1]
 [0]]


In [4]:
np.random.seed(42)

In [5]:
ip_neurons=2
hidden_neurons=3
op_neurons=1

In [6]:
W1=np.random.uniform(-1,1,size=(ip_neurons,hidden_neurons))
b1=np.random.uniform(-1,1,size=(1,hidden_neurons))

In [7]:
print(W1)

[[-0.25091976  0.90142861  0.46398788]
 [ 0.19731697 -0.68796272 -0.68801096]]


In [8]:
print(b1)

[[-0.88383278  0.73235229  0.20223002]]


In [9]:
W2=np.random.uniform(-1,1,size=(hidden_neurons,op_neurons))
b2=np.random.uniform(-1,1,size=(1,op_neurons))

In [10]:
print(W2)

[[ 0.41614516]
 [-0.95883101]
 [ 0.9398197 ]]


In [11]:
print(b2)

[[0.66488528]]


In [12]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [13]:
def sigmoid_d(x):
    return x*(1-x)

In [14]:
lr=0.1
epochs=1000

In [23]:
for epoch in range(epochs):

    hidden_ip=np.dot(inp,W1)+b1
    hidden_op=sigmoid(hidden_ip)

    final_ip=np.dot(hidden_op,W2)+b2
    final_op=sigmoid(final_ip)

    error=op-final_op

    d_op=error*sigmoid_d(final_op)
    
    hidden_error = np.dot(d_op, W2.T) 

    d_hidden=hidden_error*sigmoid_d(hidden_op)


    W2+=np.dot(hidden_op.T,d_op)*lr
    b2+=np.sum(d_op,axis=0,keepdims=True)*lr

    W1+=np.dot(inp.T,d_hidden)*lr
    b1+=np.sum(d_hidden,axis=0,keepdims=True)*lr
    if epoch % 100 == 0:
        print("Loss:", np.mean(np.square(error)))

Loss: 0.007985984357876261
Loss: 0.007610081517989526
Loss: 0.0072652310866614745
Loss: 0.006947901475039202
Loss: 0.006655061515352159
Loss: 0.006384096828888956
Loss: 0.006132742116363036
Loss: 0.005899025999021317
Loss: 0.005681225819139692
Loss: 0.005477830394117168


In [24]:
print(final_op)

[[0.07268095]
 [0.92108405]
 [0.92871258]
 [0.06756673]]
